lesson_3/food/blog/urls.py
from django.urls import path
from .views import NewsListView, RegisterNews, NewsDetailView


urlpatterns = [
    path('news-list/', NewsListView.as_view(), name='news-list'),
    path('new_news/', RegisterNews.as_view(), name='register-news'),
    path('news-list/<int:pk>/', NewsDetailView.as_view(), name='news-detail')
]

lesson_3/food/blog/models.py
from django.db import models



# Create your models here.
class Author(models.Model):
    username = models.CharField(max_length=20, verbose_name='Логин')
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='email', max_length=50)

    class Meta:
        db_table = 'author'

    def __str__(self):
        return f'{self.username}'



class News(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок', db_index=True)
    content = models.TextField(verbose_name='Содержание', default='')
    published_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    update_at = models.DateTimeField(auto_now=True)
    status_choices = [
        ('a', 'Active'),
        ('i', 'Inactive')
    ]
    activity_flag = models.CharField(max_length=1, choices=status_choices, default='i')

    author = models.ForeignKey(Author, verbose_name='автор', on_delete=models.CASCADE)


    class Meta:
        db_table = 'news'  # название базы данных
        ordering = ['-published_at'] # сначала будут новые если 'published_at' наоборот
        permissions = [
            ('can_publish', 'Может опубликовать новость')
        ]
    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):
    email = models.EmailField(max_length=50, verbose_name='email')
    username = models.CharField(max_length=20, verbose_name='логин')
    comment = models.TextField(verbose_name='комментарий')
    published_at = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name='новость')


    class Meta:
        db_table = 'comments'
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return f'{self.email}'

lesson_3/food/blog/forms.py
from django import forms
from .models import News, Comment


# class NewsForm(forms.ModelForm):
#
#
#     class Meta:
#         model = News
#         # fields = '__all__'
#         exclude = ['activity_flag']

class PostForm(forms.Form):
    title = forms.CharField(max_length=50, label='Заголовок новости: ')
    content = forms.CharField(widget=forms.Textarea, label='Содержание')
    username = forms.CharField(max_length=20, label='Логин')
    last_name = forms.CharField(max_length=20, label='Фамилия')
    first_name = forms.CharField(max_length=20, label='Имя')
    email = forms.EmailField(max_length=50, label='email')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['news', 'published_at']

lesson_3/food/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, View, DetailView
from .models import News, Author
from .forms import PostForm, CommentForm


class NewsListView(ListView):
    model = News
    template_name = 'blog/news-list.html'
    context_object_name = 'news'
    queryset = News.objects.filter(
        activity_flag='a'
    )

class NewsDetailView(DetailView):

    def get(self, request, *args, **kwargs):
        news_id = self.kwargs['pk']
        news = get_object_or_404(News,pk=news_id)

        comment_form = CommentForm()

        return render(request, 'blog/news_detail.html',
                      context={'news': news, 'comment_form': comment_form})




class RegisterNews(View):

    def get(self, request):
        news_form = PostForm()
        return render(request, 'blog/news_form.html', context={'news_form': news_form})


    def post(self, request):
        news_form = PostForm(request.POST)
        if news_form.is_valid():
            data = news_form.cleaned_data
            new_author = Author.objects.create(
                username=data['username'],
                last_name=data['last_name'],
                first_name=data['first_name'],
                email=data['email']
            )
            new_author.save()

            new_news = News.objects.create(title=data['title'], content=data['content'],
                                           activity_flag='i', author=new_author)
            new_news.save()


        return redirect('news-list')

lesson_3/food/blog/templates/blog/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<main>
    <header>
        <h1>Блог новостей</h1>
        <div class="links">
            <a href="{% url 'news-list' %}">Новости</a>
            <a href="{% url 'register-news' %}">Расскажи новость</a>

        </div>
    </header>
    <div class="container">
        {% block news_list %}
        {% endblock %}

        {% block news_form %}
        {% endblock %}



    </div>

</main>

</body>
</html>

lesson_3/food/blog/templates/blog/news-list.html
{% extends 'blog/base.html' %}

{% block news_list %}

   {% for i_news in news %}
   <a href="{% url 'news-detail' i_news.id %}">
      <div class="news">
          <h2>{{i_news.title}}</h2>
          <span>Опубликовано: {{i_news.published_at|date:"SHORT_DATE_FORMAT"}} {{i_news.published_at|time:"H:i"}}</span>
          <br>
          <span>Изменено: {{i_news.update_at|date:"SHORT_DATE_FORMAT"}} {{i_news.updated_at|time:"H:i"}}</span>
          <p>{{i_news.content|truncatewords:20}}</p>
      </div>
   </a>
   {% empty %}
   <h3>Новостей пока нет...</h3>

    {% endfor %}
{% endblock %}

lesson_3/food/blog/templates/blog/news_detail.html
{% extends 'blog/base.html' %}

{% block news_list %}

<div class="news">
    <h2>{{ news.title}}</h2>
    <span>{{news.author.username}} {{news.published_date}}</span>
    <h3>Автор: {{news.author.first_name}} {{news.author.last_name}}</h3>
    <p>{{news.content}}</p>

    <h4>Оставьте обратную связь автору:
        <a href="mailto:{{news.author.email}}">{{news.author.email}},</a>
    </h4>
    <div class="comment">
        <h3>Оставьте комментарий: </h3>
        <form method="post">
            {% csrf_token %}
            {{comment_form.as_p}}
            <button type="submit">Отправить</button>
        </form>
    </div>
</div>



{% endblock %}

lesson_3/food/blog/templates/blog/news_form.html
{% extends 'blog/base.html' %}


{% block news_form %}

    <form method="post">
        {% csrf_token %}
        {{news_form.as_p}}
        <button type="submit">Сохранить</button>

    </form>

{% endblock %}