lesson_4_auth/lesson_4_1/lesson_4_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_auth.urls'))
]

lesson_4_auth/lesson_4_1/my_auth/urls.py
from django.conf.urls.static import static
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import main_page, login_view, logout_view, MyLogoutView, register_view, RecordFormView, RecordDetailView
from django.conf import settings



urlpatterns =[
    path('', main_page, name='main'),
    # path('login', login_view, name='login'),
    path('login/', LoginView.as_view(template_name='my_auth/login.html',
     redirect_authenticated_user=True), name='login'),
    path('logout', MyLogoutView.as_view(), name='logout'),
    path('register', register_view, name='register'),
    path('record_create/', RecordFormView.as_view(), name='record_create'),

    path('record/<int:pk>/', RecordDetailView.as_view(), name='record_detail')


    ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lesson_4_auth/lesson_4_1/my_auth/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(verbose_name='birthdate')
    tel = models.CharField(max_length=16)
    news_num = models.IntegerField(default=0, verbose_name='кол-во публикаций')

    def __str__(self):
        return f'{self.user.email}'

class Record(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='профиль')
    title = models.CharField(max_length=256, verbose_name='заголовок')
    description = models.TextField(verbose_name='Содержание')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='обновлено')

    class Meta:
        db_table = 'records'
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'
        ordering = ['-created_at']

class ImagesRecord(models.Model):
    record = models.ForeignKey(Record, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='records/', null=True)

    class Meta:
        db_table = 'images2record'
        verbose_name = 'изображение'
        verbose_name_plural = 'изображения'

lesson_4_auth/lesson_4_1/my_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Record

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'last_name', 'first_name', 'password1', 'password2')

class ProfileForm(forms.ModelForm):

    birthday = forms.DateField(widget=forms.DateInput)


    class Meta:
        model = Profile
        fields = ('birthday', 'tel')


class RecordForm(forms.ModelForm):


    class Meta:
        model =Record
        exclude = ('user',)



class ImagesForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'multiple': 'multiple'}), required=False)

lesson_4_auth/lesson_4_1/my_auth/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.core.files import images
from django.shortcuts import render, redirect
from django.template import context
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.views import View

from django.views.generic import DetailView #my

from .forms  import UserForm, ProfileForm, RecordForm, ImagesForm
from .models import Profile, Record, ImagesRecord
from django.contrib import messages



def main_page(request, *args, **kwargs):
    records = Record.objects.all()[:3]
    return render(request, 'my_auth/base.html', context={'records': records})


def login_view(request, *args, **kwargs):
    if request.method == 'GET':
        return render(request, 'my_auth/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('main')

    return render(request, 'my_auth/login.html', {'error': 'auth error'})


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('main')


def logout_view(request):
    logout(request)
    return redirect('main')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            birthday = profile_form.cleaned_data['birthday']
            tel = profile_form.cleaned_data['tel']
            Profile.objects.create(
                user=user,
                birthday=birthday,
                tel=tel
            )
            username = user_form.cleaned_data['username']
            raw_password = user_form.cleaned_data['password1']
            auth_user = authenticate(username=username, password=raw_password)
            login(request, auth_user)
            return redirect('main')
        else:
            messages.add_message(request, messages.ERROR, 'Invalid fields')

    user_form = UserForm()
    profile_form = ProfileForm()
    return render(request, 'my_auth/register.html', context={
        'user_form': user_form,
        'profile_form': profile_form
    })


class RecordFormView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        record_form = RecordForm()
        image_form = ImagesForm()
        return render(request, template_name='my_auth/record_form.html',
                      context={'record_form': record_form, 'image_form': image_form})

    def post(self, request):
        record_form = RecordForm(request.POST)
        image_form = ImagesForm(request.POST, request.FILES)
        if record_form.is_valid() and image_form.is_valid():
            new_record = record_form.save(commit=False)
            new_record.user_id = request.user.profile.id
            new_record.save()
            images = request.FILES.getlist('image')
            for i_img in images:
                instance = ImagesRecord(image=i_img, record=new_record)
                instance.save()
            return redirect('main')
        return render(request, template_name='my_auth/record_form.html',
                      context={'record_form': record_form, 'image_form': image_form,
                               'error': 'Something went wrong'})


class RecordDetailView(DetailView):
    model = Record
    template_name = 'record_detail.html'
    context_object_name = 'record'

lesson_4_auth/lesson_4_1/my_auth/templates/my_auth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
</head>
<body>
    <header class="container mb-5" style="display:flex; justify-content:space-between;">
        <h1>Some App</h1>
        <div style="display:flex;">
            <a class="me-5" href="{% url 'record_create' %}">Create record</a>
            {% if request.user.is_authenticated %}
                <p class="me-2">Вы {{request.user.username}}</p>
                <a class="me-2" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="me-2" href="{% url 'register' %}">Sign up</a>
                <a class="me-2" href="{% url 'login' %}">Log in</a>
            {% endif%}

        </div>
    </header>
<main>
    {% block main %}
        <div class="container">
            {% for i_record in records %}
                <div class="container d-flex flex-column">
                    <h2>{{i_record.title}}</h2>
                    {% for i_img in i_record.images.all %}
                    <div>
                        <img src="{{i_img.image.url}}" width="500px" height="300px">
                    </div>
                    {% endfor %}
                </div>

                <p>{{i_record.description|truncatewords:50}} <a href="{% url 'record_detail' pk=i_record.pk %}">Читать далее... </a></p>

<!--                <p>{{i_record.description| truncatewords:50}} <a href="#">Читать далее... </a></p>-->
                <div class="d-flex">
                    <span class="me-2">Автор: {{i_record.user.user.email}}</span>
                    <span>Опубликовано: {{i_record.created_at}}</span>
                </div>

            {% endfor %}
        </div>
    {% endblock %}
</main>
</body>
</html>

lesson_4_auth/lesson_4_1/my_auth/templates/my_auth/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
   <form method="POST">
       {% csrf_token %}
       {{form.as_p}}
      <button type="submit">Log in</button>
<!--       <label for="login">Login: </label>-->
<!--       <input name="username" id="login" type="text">-->
<!--       <label for="password">Password</label>-->
<!--       <input name="password" id="password" type="password">-->
<!--       <button type="submit">Log in</button>-->
   </form>
   <br>
<!--   {% if error %}-->
<!--      <p style="color:red">{{error}}</p>-->
<!--   {% endif%}-->
   <a href="{% url 'register' %}">Try to sign up</a>

</body>
</html>

lesson_4_auth/lesson_4_1/my_auth/templates/my_auth/record_form.html
{% extends 'my_auth/base.html' %}



{% block main %}
   <div class="container">
      <h2>Create record</h2>
       <form method="post" enctype="multipart/form-data">
           {% csrf_token %}
           {{record_form.as_p}}
           {{image_form.as_p}}
           <button type="submite" class ="btn btn-primary">Create</button>
       </form>
   <p>{{error}}</p>
   </div>
{% endblock %}

lesson_4_auth/lesson_4_1/my_auth/templates/my_auth/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
</head>
<body>
<main>
    <div style="margin: 0 auto; max-width: 800px;">
        <h1>Registration</h1>
        <form method="post">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <button type="submit">Sigh up</button>
        </form>
       {% if messages %}
          {% for message in messages %}
        <p style="color:red;">{{message}}</p>
          {% endfor %}
       {% endif %}
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.min.js"></script>
<script>
<!--    $("#id_birthday").click(function(){$(this).setCursorPosition(0);}).mask("9999-99-99");-->
    $("#id_tel").click(function(){$(this).setCursorPosition(1);}).mask("+7(999) 999-9999");
</script>
</body>
</html>

lesson_4_auth/lesson_4_1/my_auth/templates/record_detail.html
{% extends 'my_auth/base.html' %}


{% block main %}
    <div class="container">
        <h2>{{ record.title }}</h2>
        {% for i_img in record.images.all %}
            <div>
                <img src="{{i_img.image.url}}" width="500px" height="300px">
            </div>
        {% endfor %}

        <p>{{ record.description }}</p>
        <div class="d-flex">
            <span class="me-2">Автор: {{record.user.user.email}}</span>
            <span>Опубликовано: {{record.created_at}}</span>
        </div>
    </div>
{% endblock %}